#title in header
title: "Suda Notes"

#main info
#owner
owner: "Hi, I'm Hiro"
email: ecdohiro@gmail.com
info: "A web developer | Product/Project Manager."
#description
desc: "Developing Laravel Suda and related projects."

#works and project
project_title: "Working"
project_list:
  - {name: Suda, link: https://suda.gtd.xyz}
  - {name: GTD, link: https://app.gtd.xyz}

#menu
menu:
  Service: /Service
  About: /About

#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: C1AC9E

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/daocatt
linkedin: https://linkedin.com/in/ecdohiro
twitter: https://twitter.com/ecdohiro
# instagram: https://instagram.com/adisaktijrs
telegram: https://t.me/sudanotes

# Misc
nanobar: /js/nanobar.min.js
switch_light: ðŸŒž
switch_dark: ðŸŒ‘

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: suda-notes
